### ISSUE TITLE
Rspec subject and let blocks do not memoize (some?) Stripe objects made by StripeMock

### ISSUE THREAD

**Issue by reconstructions** [rebelidealist/stripe-ruby-mock#253] opened 2015-08-23 18:03 UTC
I have been having a problem in Rspec tests with the creation of duplicate Stripe::X objects by StripeMock.  If I do this in an Rspec test:

```ruby
require 'rails_helper'
require 'stripe_mock'

describe SubscriptionsController, :type => :controller, :controller => true do
  
  before { StripeMock.start }
  
  before do
    @user = create(:user)
    sign_in_user(@user, no_capybara: true)
  end

  after { StripeMock.stop }
 
  describe "GET#new" do
 
    let!(:plan) {
      Stripe::Plan.create(
        :amount => 300,
        :interval => "month",
        :name => "Musician's Membership",
        :currency => "usd",
        :id => "plan_musician" )
    }
 
    before{ get :new }
 
    it "makes  the plan object more than once!" do
      expect(assigns(:stripe_plan)).to eq(plan)
    end
  end
end
```

I get the following error:

```
Failure/Error: expect(assigns(:stripe_plan)).to eq(@plan)

       expected: #<Stripe::Plan:0x859ce160 id=plan_musician> JSON: {
         "id": "plan_musician",
         "interval": "month",
         "name": "Musician's Membership",
         "amount": 300,
         "currency": "usd",
         "object": "plan",
         "livemode": false,
         "interval_count": 1,
         "trial_period_days": null
       }
            got: #<Stripe::Plan:0x85b42b40 id=plan_musician> JSON: {
         "id": "plan_musician",
         "interval": "month",
         "name": "Musician's Membership",
         "amount": 300,
         "currency": "usd",
         "object": "plan",
         "livemode": false,
         "interval_count": 1,
         "trial_period_days": null
       }

       (compared using ==)

       Diff:
```

The controller code is not much:

```ruby
def new
  @stripe_plan = Stripe::Plan.retrieve('plan_musician')

  respond_to do |format|
    format.html
  end
end
```

In other more complex cases the two objects will become inconsistent and cause tests to fail when they shouldn't.  I am having the problems in model, controller, and integration tests.  As far as I can tell I am only seeing duplicate object created when I am using StripeMock.

I have tried multiple combinations of before and subject blocks, and moving them around can sometimes make this problem go away, but it is trial and error and in some cases I am putting a lot of time into this without finding a workaround.  

All my gems are up to date (rails (4.2.3), rspec-rails (3.3.3), stripe-ruby-mock (2.1.1), stripe (1.20.1))

I am hoping this is some simple mistake I am making.  Thanks in advance for any help!

**Comment by kathyonu** [comment] 2015-08-23 20:19
First error I see is your own duplication : `describe SubscriptionsController, :type => :controller, :controller => true do`

It should be `describe SubscriptionsController, controller: true do`
Also, the `controller: true` is only required if you do not have this in your `rails_helper.rb` file : 
```ruby
  # If true, the base class of anonymous controllers will be inferred automatically.
  # This will be the default behavior in future versions of rspec-rails.
  config.infer_base_class_for_anonymous_controllers = true
```
Make sure you use one or the other, not both.
Also while both work, I changed your hash to new format ..
key: 'value'  is new form .. or ..
key: :value  is new form
:key => 'value is old form
:key => :value is old form

**Comment by kathyonu** [comment] 2015-08-23 20:27
Please forgive, my first response proves a bit hasty.  I think the problem is here : 
`expect(assigns(:stripe_plan)).to eq(plan)`
change that to : 
`expect(assigns(:plan)).to eq(plan)`
Hope that helps

**Comment by reconstructions** [comment] 2015-08-24 01:27
@kathyonu, thanks for the feedback.  I am still cleaning out all the old form hashes, this is one of the last, I will fix it, thx for that.  

I'll see if your suggestions clean up the :type stuff, I use tags a lot but only added that so I could get my tests running in Rspec 3, would be happy to get them out of there.  

I think my controller variable test is correct with `assigns(:stripe_plan)`, however, `@stripe_plan` is the variable in the controller #new action, as posted above.

I sure hope someone can help with these duplicate object instantiations.  I am getting lots of them, only some of which I can guess my way around... Thanks!

**Comment by reconstructions** [comment] 2015-08-24 01:47
Okay, this is off topic, and I don't want to distract from the real problem, but here is why I have this in my controller test: `:type => :controller, :controller => true do`.  There is a (problem)[http://stackoverflow.com/questions/27284657/undefined-method-env-for-nilnilclass-in-setup-controller-for-warden-error] with Devise controller test helpers.  If `infer_base_class_for_anonymous_controllers` is true they aren't found, and I can't test my controllers.  Probably Devise doesn't pick this up yet.  When I migrated to Rspec 3.0 I had to set `infer_base_class` to false to override the default true, and I also have to have the explicit type.  Could be a Gordian knot there to try and cut, but unlike StripeMock making two of things, it isn't breaking my tests.

**Comment by kathyonu** [comment] 2015-08-24 04:00
@reconstructions this code creates a `plan` 
```ruby
let!(:plan) {
      Stripe::Plan.create(
        :amount => 300,
        :interval => "month",
        :name => "Musician's Membership",
        :currency => "usd",
        :id => "plan_musician" )
    }
```
I share a passing test to demonstrate, notice how `stripe_helper` is what is being created, and later used one time : 
```ruby
require 'stripe_mock'
include Warden::Test::Helpers
Warden.test_mode!

describe 'Subscription API', live: true do
  let(:stripe_helper) { StripeMock.create_test_helper }

  before(:each) do
    StripeMock.start
  end

  after(:each) do
    StripeMock.stop
    Warden.test_reset!
  end

  it 'creates a stripe plan' do
    plan = stripe_helper.create_plan(id: 'my_plan', amount: 1500)
    # The above line creates / mocks / replaces the following:
    # plan = Stripe::Plan.create(
    #   id: 'my_plan',
    #   name: 'StripeMock Default Plan ID',
    #   amount: 1500,
    #   currency: 'usd',
    #   object: 'plan',
    #   livemode: false,
    #   interval: 'month',
    #   interval_count: 1,
    #   trial_period_days: null
    # )
    # any variable of plan can now be tested
    expect(plan.id).to eq 'my_plan'
    expect(plan.amount).to eq 1500
    expect(plan.currency).to eq 'usd'
    expect(plan.interval).to eq 'month'
    expect(plan.interval_count).not_to eq 2
    expect(plan.trial_period_days).not_to eq 7
  end
```
Hope this helps

**Comment by kathyonu** [comment] 2015-08-24 04:03
@reconstructions  You can also address questions here : https://gitter.im/rebelidealist/stripe-ruby-mock

**Comment by reconstructions** [comment] 2015-08-25 14:30
Thanks for the Gitter tip.  Right now I not sure whether this a problem with usage or the StripeMock library, but for sure that will be useful.  Assuming this controller test:

```ruby

require 'rails_helper'
require 'stripe_mock'

describe SubscriptionsController, :type => :controller, :controller => true do
  
  before(:each) do
    StripeMock.start
  end

  let(:stripe_helper) { StripeMock.create_test_helper }

  after(:each) do
    StripeMock.stop
    # Warden.test_reset!
  end

  ....... tests here .......
  
end

```

If I put in this test:

```ruby
describe "GET#new" do

  before { get :new }

  it "fails because the plan doesn't exist when 'get :new' is called" do
    
    # this fails:
    plan = stripe_helper.create_plan(id: 'plan_musician', amount: 1500)
    expect(assigns(:stripe_plan)).to eq(plan)
    
    # In a controller spec a plan can't be created in an "it" block
    # The plan wouldn't exist when { get :new } was called:
    # => Failure/Error: before(:each){ get :new }
    # => Stripe::InvalidRequestError:
    # => No such plan: plan_musician
  end
end
```

The controller code is the same posted above.  I have `before_action :authenticate_user!` turned off in the controller, so I think we can rule out an auth problem.

But I can't find any alternative that doesn't fail or create duplicate objects:

```ruby

describe "GET#new" do

  before { 
    @plan = stripe_helper.create_plan(id: 'plan_musician', amount: 1500)
    get :new 
  }
  # the following fails because two plan objects are made:
  # expected: #<Stripe::Plan:0x81d80528 id=plan_musician> JSON:
  # got: #<Stripe::Plan:0x81c89188 id=plan_musician> JSON:

  it "the controller instance variable is set with a different plan object" do
    expect(assigns(:stripe_plan)).to eq(@plan)
  end
end

```
I can't use `let` in a before block, and if I try a hail mary and use `subject` there I get a wrong number of arguments error:

```ruby
before {
  subject(:plan){ 
    stripe_helper.create_plan(id: 'plan_musician', amount: 1500) 
  }
  get :new 
}
# => wrong number of arguments (1 for 0)
```

If I try this:

```ruby
subject(:plan) do # or 'let(:plan) do', or 'let!(:plan) do'
  stripe_helper = StripeMock.create_test_helper
  plan = stripe_helper.create_plan(
    id: 'plan_musician', 
    amount: 1500)
end

before {
  plan
  get :new 
}

# then it fails because two plans are made:
# expected: #<Stripe::Plan:xxxxxxxxx id=plan_musician> JSON:
# got: #<Stripe::Plan:xxxxxxxxx id=plan_musician> JSON:
it "fails because `subject(:plan) do not return a plan" do
  expect(assigns(:stripe_plan)).to eq(plan)
end
```
This also fails:

```ruby
def plan
  stripe_helper = StripeMock.create_test_helper
  plan = stripe_helper.create_plan(
    id: 'plan_musician', 
    amount: 1500)
end

before {
  @plan = plan
  get :new 
}

# fails with two plans:
# expected: #<Stripe::Plan:xxxxxxxxx id=plan_musician> JSON:
# got: #<Stripe::Plan:xxxxxxxxx id=plan_musician> JSON:
it "plan already exists" do
  expect(assigns(:stripe_plan)).to eq(@plan)
end
```
Those are all the work arounds I have tried for this.  I would be interested to hear if other  could repeat them, so I could rule out any problem with my Rails or Rspec config or development env.  Baring that, it is unclear to me how you could make one and only one plan in a controller spec.  If it was a question of usage, I agree Gitter would be the best place for this, but right now I am not sure about that.

**Comment by kathyonu** [comment] 2015-08-25 15:11
@reconstructions Thank you for your kind responses to why what is what. Is this resolved ? Can this issue be closed ?

**Comment by reconstructions** [comment] 2015-08-25 17:02
The syntax you suggest for creating a plan does not work for me in controller specs, as shown above.  If StripeMock is not intended to work in controller specs, then I supposed this could be closed.  If there is another way of doing this, I think it would be worthwhile sharing it here before closing this.  Until someone else succeeds or fails in repeating it, the question of whether it is definitely StripeMock behavior can't be closed.  If it is StripeMock behavior and not intended, then it is a bug, and this shouldn't be closed.

**Comment by reconstructions** [comment] 2015-08-29 14:07
I have four or five other errors I am encountering in fairly complicated controller and integration specs.  They all share the common cause of failure that when I get in there with pry, there are no StripeMock objects, duplicate StripeMock objects, or the correct StripeMock objects but not properly associated.  I think issue #182 sounds like another user encountering similar problems.  If I see a problem like #253, that looks should be similarly easy to reproduce, I will add it to issues.  Assuming this doesn't get closed.

**Comment by kathyonu** [comment] 2015-08-29 17:54
@reconstructions  regarding #182 #253 I am the one who asked about closing, and I agree it should not to be closed yet. I too have run into these same difficulties and more and I have not been able to get the above actions and tests passing, no matter what I do. The solution, I believe, is to dig deep into stripe-ruby-mock, and set up these endpoints so they mirror Stripe responses properly, and .. inter-relate as objects with each other as Stripe does. That is what I am learning / working to do. If you are interested, may I recommend forking the stripe-ruby-mock repository and tracing these difficulties deeper into the gem code and, if you know how to fix .. do so and issue a Pull Request. A real treasure trove is here [stripe-ruby-mock/lib/stripe_mock/data.rb](https://github.com/rebelidealist/stripe-ruby-mock/blob/master/lib/stripe_mock/data.rb) Also, @alexmamonchik recommended I read [Implementing a new behavior](https://github.com/rebelidealist/stripe-ruby-mock/wiki/Implementing-a-New-Behavior)  Last night, for the first time ever, I learned how to run tests in our fork of the gem.  I never knew you could do that.

**Comment by reconstructions** [comment] 2015-09-10 03:14
@kathyonu thanks for all your hard work on StripeMock, particularly on updating the gem to the newest Stripe version.  Great tips on working on a fork of the gem as well.  I have been trying to track down for certain which framework is causing this duplication of objects, and it is a little mysterious.  I have been trying for figure out why I am having an apparently similar problem with duplicate Stripe::Customer objects when my Selenium tests are running against the Stripe server without StripeMock.  The app works fine in production but breaks because of duplicate Stripe::Customer objects (possibly cause by duplicate user objects) when running using rSpec and Selenium.  I might consider pinning this one on FactoryGirl, except the above example doesn't use it.  Can't rule out rSpec.  But since my app is super complicated, I think that unless the two problems have different causes, the above example is the best change of getting to the bottom of it.  It would be interesting to run the above test against the Stripe server itself.  That will be my next move.

**Comment by louim** [comment] 2015-09-28 19:31
@reconstructions Not quite sure what you are trying to do in the first example of the issue. Could you detail a bit more what you are trying to test / achieve?

In your example, the test fail because in your controller you create an object, and in the test you create another object. Those are two different object, so the ID wont match.

I think what you want to do is check for object attribute, ex: 

```ruby
describe "GET#new" do
  before{ get :new }

  it "create a plan with the correct properties!" do
    expect(assigns(:stripe_plan)).to have_attributes(:amount => 300,
      :interval => "month",
      :name => "Musician's Membership",
      :currency => "usd",
      :id => "plan_musician")
  end
end
```

**Comment by reconstructions** [comment] 2015-09-29 01:40
Good question, but correct me if I am wrong, isn't the expected behavior for a subject or let block to execute its code once and memoize the result for the duration of an example, which would mean that StripeMock should only be creating the object once?  

Since I am using state machines, I have some fairly complex setup which I need to do each time I create a Card object and its associations.  If I did all this setup in each test, I would be adding 7 lines of code to each of my 30 examples, just to mock up identical objects.  So to keep things DRY I mock my objects in a subject block accessible to all my examples, instantiate it in a before block, and use let to modify the subject block as needed for different kinds of test.  

I use this pattern in hundreds of other controller test subject blocks with FactoryGirl, which if I am not mistaken returns a reference to the object memoized when the subject is first run.  Perhaps StripeMock is enforcing the use case where plans (and tokens?) can only be made in examples?  Or perhaps there is a way to do this in a subject block shared by all examples that I haven't figured out, in which case knowing a work around would close this issue for me.  

I think there are good reasons to be able to define a plan once for all examples, however, and certainly there aren't constraints that prevent me from mocking tests this way outside of StripeMock.  In the following test, for example (which is like most of mine), I think there are pretty good reasons for this approach:

```ruby
describe BandsController, :type => :controller do

  # This controller uses Kaminari paging, so it has to be able to return paged
  # collections for the positions where #update and #create actions 
  # insert modified or added bands.  Obviously this is not setup it makes sense to 
  # do in each example:
  subject(:bands) do

    bands = [ ]
    ["Alpha", "Bravo", "Charlie", "Delta", "Echo", "Foxtrot", "Golf", "Hotel", "India", "Juliet", "Kilo", "Lima", "Mike", "November", "Oscar", "Papa", "Quebec", "Romeo", "Sierra", "Tango", "Uniform", "Victor", "Whisky", "Xray", "Yankee", "Zulu"].each do |str|
      bands << create(:band, band_name: str)
    end
    bands
  end

  # 
  # These attributes are used in all #create and #update examples.  Not DRY to
  # do it more than once.  Let is used to change attributes in example
  # blocks, which is very readable, concise, and DRY.
  subject(:band_attributes) do
    attributes_for(:band,
      band_name: band_name_attr
    ).merge(musician_ids: musicians_ids_attr)
  end
  
  # More setup that only needs to be done once.
  subject(:musicians) do
    [ create(:musician), create(:musician) ]
  end
  
  describe "POST#create" do
    # if subject(:bands) isn't called 'before', the queries FactoryGirl
    # uses to setup the bands will count towards the 'to make (12) database'
    # queries test. By calling and memoizing the result of bands and
    # band_attributes in a before block, the objects are made and the collection
    # memoized.  Therefore only the queries associated with the action 
    # are counted.  A pretty useful test for a controller action.

    before { bands; band_attributes }

    subject(:create_band) do
      xhr :post, :create, { band: band_attributes }
    end

    context "when valid attributes are submitted," do

      let(:band_name_attr){ "Led Zeppelin" }
      let(:musicians_ids_attr){ [ musicians[0].id, musicians[1].id] }

      it 'to make (12) database queries' do
        expect { create_band }.to make_database_queries(count: 12)
      end
    end
  end
end
```

**Comment by reconstructions** [comment] 2015-09-29 01:43
From the Rspec [doc page](http://rspec.info/documentation/3.3/rspec-core/RSpec/Core/MemoizedHelpers/ClassMethods.html) on let (which is mostly identical to subject):

```ruby
describe Thing do
  let(:thing) { Thing.new }

  it "does something" do
    # First invocation, executes block, memoizes and returns result.
    thing.do_something

    # Second invocation, returns the memoized value.
    thing.should be_something
  end
end
```

**Comment by reconstructions** [comment] 2015-09-29 13:26
Just to clarify what is going on under the hood for me right now, if I call a Stripe::Plan.creating subject block in the before block of an example, the subject block will return the stripe plan, but a controller variable assigned with Stripe::Plan.all.data will have a different second object instance.  Subject is supposed to memoize the result of the first invocation, so one would expect that only one Stripe::Plan.create would have been created, no matter how many times subject had been called.

**Comment by louim** [comment] 2015-09-29 15:17
Ill try to explain a bit more why the example doesn't work. `stripe-ruby-mock` act as a simulated backend for Stripe. When in your example you do: 

```
    let!(:plan) {
      Stripe::Plan.create(
        :amount => 300,
        :interval => "month",
        :name => "Musician's Membership",
        :currency => "usd",
        :id => "plan_musician" )
    }
```

It does *the let block* → *stripe ruby gem* → *stripe ruby mock gem* →  *stripe ruby gem* → *the result of the call is stored in your let `:plan`*

This is like doing an HTTP call to Stripe API, and getting the confirmation that your plan was created. When this call get back from Stripe, the Stripe gem convert the hash returned to an object, which is stored in your `let`.

After that, when you do in your controller:

```
@stripe_plan = Stripe::Plan.retrieve('plan_musician')
```

It does  *stripe ruby gem* → *stripe ruby mock gem where the plan is stored* →  *stripe ruby gem* → *the result of the call is stored in your `@stripe_plan`*

Then again it's like doing another HTTP call to the Stripe API. The Stripe gem will again process the returned hash from the mock library and create an object with it. **It will not be the same object that the first call returned, because the Stripe library just did another call to the API (which in our case is mocked by this gem)**

Your example would produce the same results with the live API. You can try it with:


```
require "stripe"
Stripe.api_key = "sk_test_yourkey"

plan = Stripe::Plan.create(
  :amount => 300,
  :interval => "month",
  :name => "Musician's Membership",
  :currency => "usd",
  :id => "plan_musician"
)

retrieved_plan = Stripe::Plan.retrieve('plan_musician')

plan == retrieved_plan
```

You'll get `false` because the object ID won't match. So you are right about how memoized `let` works, but since it is a simulated API call, object are recreated on each calls. It's not the same that when you do it in your own code, where an object doesn't get serialized and deserialized over an http call. `stripe-ruby-mock` has nothing it can do for that.

In case you are curious how the whole process happens in the Stripe gem, check https://github.com/stripe/stripe-ruby/blob/master/lib/stripe/util.rb#L54-L64. You can alse put a `debugger` statement in your controller and follow the flow of execution. 

Let me know if somethings not clear! :smile:

**Comment by reconstructions** [comment] 2015-09-29 16:18
Truly awesome explanation, which is greatly appreciated.  It is clear to me now that this is intended behavior, not a bug.  

I think the reason this was not clear to me is it departs from the conventions used in database mocking and RSpec generally.  For example, in the same way that an API will give you a response every time you call it, a db create action normally instantiates one new object every time you call it.  But RSpec with FactoryGirl changes this behavior to take advantage of the intended use of subject and let blocks, and instead makes one object the first time you call a memoizing block, and afterwards returns that object every time you call it.

This behavior makes a lot of sense in terms of keeping tests DRY, because it allows you to have the same object end up on both the L and R side of an expectation, thus avoiding duplicate object instantiation or being prevented from testing object equivalence.  It also allows you to do mocking once and share the results throughout multiple tests while changing single attributes, which is the whole purpose of subject and let.

For sure RSpec and FactoryGirl change conventional expectations about db behavior to make testing easier.  It seems to me that the rational for having subject and let memoize object instantiations applies equally to API calls which make objects on a remote service.  If this is a convention for mocking API's, then I think this is a learning moment for me.  If not, then I think maybe better documenting the way this departs from convention is really essential.  If StripeMock is setting a precedent, I think the RSpec/FactoryGirl convention makes more sense, is there for a reason, and should be adopted.

Now that I understand what is going on, I will take another look at the different tests where this behavior is preventing me from drying out my code, and see what the most concise work-around might be.  More on that later if I have anything worth sharing... 

Thanks for the great explanation, and hopefully this will help novice users other than myself understand what StripeMock is up to!

**Comment by reconstructions** [comment] 2015-09-29 16:48
OK, forgive me if I am missing something really obvious, but the following should only be making one API call, and therefore only one Stripe object, right?  The expectation L and R values are both being queried from the API, and the before block should only run once, correct?

```ruby
#.... subscriptions_controller_spec.rb:

before do
  Stripe::Plan.create(
    :amount => 300,
    :interval => "month",
    :name => "Musician's Membership",
    :currency => "usd",
    :id => "plan_musician" )
end

#....

subject(:plan) {
  Stripe::Plan.retrieve("plan_musician")
}

# .....

it "makes  the plan object more than once!" do
  expect(assigns(:stripe_plans)).to eq(plan)
end

#...  subscriptions_controller.rb:

def new
  @stripe_plans = Stripe::Plan.all.data
end

#..... test result:

# Failure/Error: expect(assigns(:stripe_plans)).to eq(plan)

# expected: #<Stripe::Plan:0x84a489ac id=plan_musician>
# got: #<Stripe::Plan:0x84a8d4a8 id=plan_musician>
```

**Closed** 2015-09-29 16:52 UTC

**Comment by reconstructions** [comment] 2015-09-29 17:17
Hmm, I guess Stripe behavior is to instantiate a different object on each call:

```ruby
Stripe::Plan.retrieve('musician_plan')
=> #<Stripe::Plan:0x851b0d84 id=musician_plan>
Stripe::Plan.retrieve('musician_plan')
=> #<Stripe::Plan:0x85178d6c id=musician_plan>
```
So returning the same memoized object from a subject block would be mocking different behavior from Stripe.  Sorry to think out loud, thanks for all the tips, and hope this helps someone else understand how StripeMock works.

**Comment by kathyonu** [comment] 2015-09-29 17:26
@louim  Priceless explanations, thank you very much from a novice.
@reconstructions and no apology required for thinking out loud, for I never once thought of running `Stripe::Plan.retrieve('musician_plan')` twice in a row and comparring the object number from Stripe.  I did come to the conclusion that nowhere could I see that stripe-ruby-mock or Stripe check the object_id of the plan, and so I was deep into what worth, that test?  Glad this is resolved.
